# Generated by Django 6.0.6 on 2026-09-25 01:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0021_dealsource_offer_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=160)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'contact_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BranchFulfillmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('pickup_radius_km', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('local_same_day_enabled', models.BooleanField(default=True)),
                ('local_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('local_max_delivery_hours', models.PositiveIntegerField(default=24)),
                ('nationwide_enabled', models.BooleanField(default=False)),
                ('nationwide_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('nationwide_max_delivery_hours', models.PositiveIntegerField(default=72)),
                ('customer_cancel_policy', models.CharField(choices=[('disabled', 'Customer cannot cancel'), ('window_minutes', 'Cancel within window')], default='window_minutes', max_length=32)),
                ('customer_cancel_window_minutes', models.PositiveIntegerField(default=30, help_text='Used when customer_cancel_policy is window_minutes.')),
                ('bank_transfer_enabled', models.BooleanField(default=False)),
                ('bank_transfer_instructions', models.TextField(blank=True)),
                ('cash_on_pickup_enabled', models.BooleanField(default=True)),
                ('cash_on_delivery_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'business categories',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_normalized', models.CharField(db_index=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('awaiting_payment', 'Awaiting payment'), ('payment_submitted', 'Payment submitted'), ('paid_confirmed', 'Payment confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for pickup'), ('out_for_delivery', 'Out for delivery'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'In-store pickup'), ('local_same_day', 'Local / same-day delivery'), ('nationwide', 'Nationwide / standard delivery')], max_length=32)),
                ('payment_method', models.CharField(choices=[('cash_on_pickup', 'Cash on pickup'), ('cash_on_delivery', 'Cash on delivery'), ('bank_transfer', 'Bank transfer'), ('stripe', 'Stripe'), ('jazzcash', 'JazzCash')], max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_address_text', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('customer_cancel_allowed', models.BooleanField(default=True)),
                ('customer_cancel_until', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business'), ('system', 'System')], max_length=16)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-placed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliverySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_type', models.CharField(max_length=32)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_delivery_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('promised_by', models.DateTimeField(blank=True, null=True)),
                ('branch_city_id', models.IntegerField(blank=True, null=True)),
                ('branch_city_name', models.CharField(blank=True, max_length=80)),
                ('customer_city_id', models.IntegerField(blank=True, null=True)),
                ('customer_city_name', models.CharField(blank=True, max_length=80)),
                ('pickup_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('unit_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_proofs/')),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductEngagementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_gallery/')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='discounts_d_user_id_bb7162_idx',
            old_name='discounts_d_user_id_7c8f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='discounts_n_user_id_ded26d_idx',
            old_name='discounts_n_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='discounts_n_user_id_42d7cc_idx',
            old_name='discounts_n_user_id_read_at_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='discounts_o_review__be92e5_idx',
            old_name='discounts_o_review__idx',
        ),
        migrations.AddField(
            model_name='business',
            name='online_coverage',
            field=models.CharField(choices=[('city', 'City'), ('country', 'Whole country')], default='city', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='presence_mode',
            field=models.CharField(choices=[('online_only', 'Online only'), ('instore_only', 'In-store only'), ('hybrid', 'Online and in-store')], default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discounts.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_businesses', to='discounts.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
        migrations.AddField(
            model_name='branchcontact',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='discounts.branch'),
        ),
        migrations.AddField(
            model_name='branchfulfillmentsettings',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_settings', to='discounts.branch'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_categories', to='discounts.business'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_links', to='discounts.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='businesses', through='discounts.BusinessCategory', to='discounts.category'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='discounts.branch'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discounts.cart'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='discounts.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='discounts.city'),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_businesses', to='discounts.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='discounts.country'),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_businesses', to='discounts.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='discounts.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='discounts.business'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdeliverysnapshot',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_snapshot', to='discounts.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discounts.order'),
        ),
        migrations.AddField(
            model_name='orderpaymentproof',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='discounts.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='products', to='discounts.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='discounts.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='discounts.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_product', to='discounts.offer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='productengagementstats',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_stats', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productviewevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='discounts.product'),
        ),
        migrations.AddField(
            model_name='productviewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_view_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='branchcontact',
            constraint=models.UniqueConstraint(fields=('branch', 'contact_type', 'value'), name='unique_branch_contact_value'),
        ),
        migrations.AddConstraint(
            model_name='businesscategory',
            constraint=models.UniqueConstraint(fields=('business', 'category'), name='unique_business_category'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'name_normalized'), name='unique_city_per_country'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-placed_at'], name='discounts_o_user_id_6e319e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='discounts_o_busines_047211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='discounts_o_branch__fdddc4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_enabled', 'is_available'], name='discounts_p_busines_0e4654_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='discounts_p_categor_33f6ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'branch'), name='unique_cart_product_branch'),
        ),
        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='productviewevent',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product', 'viewed_on'), name='unique_product_view_per_user_day'),
        ),
    ]
