# Generated by Django 6.0.6 on 2026-09-29 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0030_product_reviews_and_rating_aggregates'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchfulfillmentsettings',
            name='same_day_cutoff_time',
            field=models.TimeField(blank=True, help_text='Optional same-day order cutoff (local). Promised by = that time today, else end of day.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete timestamp; keeps order history.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='is_escalated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orderproblemreport',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderproblemreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproblemreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order_problem_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderproblemreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='orderproblemreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('support', 'Support')], default='owner', help_text='Staff role: Owner (full) or Support (orders/reports write, read-only elsewhere).', max_length=16),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProblemReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_problem_report_notes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='discounts.orderproblemreport')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='discounts.order')),
            ],
            options={
                'verbose_name_plural': 'order status histories',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
